### PR TITLE
Improved Authentication and Navigation

### PR DESCRIPTION
**Pull request by jclaerhout**
Improved Authentication and Navigation

This pull request enhances the RoomMapping app by refining user authentication. Users are seamlessly directed to the login page on launch, and after login, the navbar transforms to reflect the authentication state. The "Login" button becomes "Logout," and a new "My Maps" button appears for easy navigation to the user's scanned maps. These changes provide a smoother and more intuitive user experience.

### CODE REVIEW

**Comment by Euan-lc** [comment]
While testing the registration i notice that you are sent back to the login page after having registered however you can already see the "Mes cartes" and "Se deconnecter" buttons. It would be better if you were redirected to the homepage.

image

**Comment by Euan-lc** [comment]
Would it be more interesting to have a "Mon compte" button instead of the "Se deconnecter" button ? This button would lead to a page on which you could change your account details, log out and delete your account.

**Comment by Euan-lc** [comment]
I was also able to register an account with firstname 69 lastname 420 and a fictive bruh@gmail.com. It would be good to implement some checking for the first and lastname as well as email confirmation to activate an account.

**Comment by jclaerhout** [comment]
Regarding the return to the login page after registration, you're absolutely right. I was initially unaware of Firebase's account creation behavior, but I've addressed it. Users are now redirected to the home page after registration.

The idea of adding a "My Account" button is excellent. I've implemented this feature, and now, the "My Account" page displays the connected user's email, with a "Logout" button for easy disconnection.

As for the validation of the first and last name fields, it's now in place. These fields only accept letters and must contain at least 2 characters.

Regarding email address verification, I agree that it's a critical step. To ensure a careful implementation, I will create a new User Story dedicated to this feature, as the current changes need to be merged promptly into the E-Client branch to ensure smooth progress.

**Comment by Euan-lc** [comment]
Okay, that all looks good. We should add a user story for fleshing out the account page as well as implementing the forgotten password feature

**Comment by Slywoud** [comment]
The pull request looks good and works as intented 👍

**Pull request merged**
