### PR TITLE
(US-20) Zoom Functionality

### PR DESCRIPTION
**Pull request by Slywoud**
# Zoom Functionality

## Description:
This pull request  implements a new zoom functionality  to allow a user after scanning the QR code of a map to zoom/dezoom on the map using React.

## Screenshot     
   
image

### CODE REVIEW

**Comment by AlassaneWone** [comment]
everything looks fine to me. The code is clear and works fine.

**Comment by AlassaneWone** [comment]
I noticed that you have react based css in your zoom.js file and classic css in your zoom.css file. Shouldn't you centralize your css and only use one format ?

**Comment by Slywoud** [comment]
Fixed

**Comment by AlassaneWone** [comment]
ok, looks good to me.

**Pull request merged**
